### ISSUE TITLE
楼主你好，看到你的分享，按照步骤来做的，npm intsall都报错？

### ISSUE THREAD

**Issue by kkkk3q** [huangshuwei/webpackForSPA#5]
![image](https://user-images.githubusercontent.com/17720045/29009541-b434e4f4-7b56-11e7-8905-adf48b695778.png)

**Comment by huangshuwei** [comment]
你这个应该是本地环境的问题，试下这个：
https://github.com/npm/npm/issues/16861

另外建议webpack1 升级到 webpack3

这是webpack3 的实例：
https://github.com/huangshuwei/webpack3-vue2-demo

**Comment by kkkk3q** [comment]
可以了，3q

**Comment by kkkk3q** [comment]
这个能结合vue开发吗？

**Comment by huangshuwei** [comment]
可以的
